name: wherehome
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  mapbox_maps_flutter: ^2.0.0
  permission_handler: ^11.3.1
  location: ^6.0.1
  latlong2: ^0.9.1
  provider: ^6.1.2
  easy_localization: ^3.0.7
  image_picker: ^1.1.2
  mapbox_search: ^4.2.2
  auto_size_text: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  shared_preferences: ^2.2.3
  package_info_plus: ^8.0.0
  flutter_local_notifications: ^17.1.2
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/fonts/
    - assets/images/
    - lib/data/repositories/
    - assets/countries_flags/
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter-Black.ttf
          weight: 900
    - family: KodeMono
      fonts:
        - asset: assets/fonts/KodeMono/KodeMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/KodeMono/KodeMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/KodeMono/KodeMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/KodeMono/KodeMono-Bold.ttf
          weight: 700

