const List<String> listOfeatures = [
  'Garage',
  'Swimming Pool',
  'Balcony',
  'Garden',
  'Fenced Yard',
  'Basement',
  'Fireplace',
  'Central Heating',
  'Air Conditioning',
  'Solar Panels',
  'Hardwood Floors',
  'Fitness Center',
  'Tennis Court',
  'Playground',
  'Laundry Room',
  'Office/Study Room',
  'Walk-in Closets',
  'Smart Home Technology',
  'Security System',
  'Wheelchair Accessible',
  'High Ceilings',
  'Elevator',
  'Corner Unit',
  'Waterfront',
  'Home Theater',
  'Guest House',
  'Wine Cellar',
  'Sauna',
  'Skylights',
  'Patio/Deck',
];
